project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "1a Geospatial Data Wrangling"
          href: "hands_on_ex/hands_on_ex01/hands_on_ex01.1.html"
        - text: "1b Choropleth Mapping"
          href: "hands_on_ex/hands_on_ex01/hands_on_ex01.2.html"
        - text: "2a 1st Order Spatial Point Patterns Analysis Methods"
          href: "hands_on_ex/hands_on_ex02/hands_on_ex02.1.html"
        - text: "2b 2nd Order Spatial Point Patterns Analysis Methods"
          href: "hands_on_ex/hands_on_ex02/hands_on_ex02.2.html"
        - text: "3 Network Constrained Spatial Point Patterns Analysis"
          href: "hands_on_ex/hands_on_ex03/hands_on_ex03.html"
        - text: "4 Spatial Weights and Applications"
          href: "hands_on_ex/hands_on_ex04/hands_on_ex04.html"
    - text: "In-class Exercises"
      menu:
        - text: "1 Geospatial Analytics"
          href: "in_class_ex/in_class_ex01/in_class_ex01.html"
        - text: "2 Spatial Point Patterns Analysis"
          href: "in_class_ex/in_class_ex02/in_class_ex02.html"
        - text: "3 Network Constrained Spatial Point Patterns Analysis"
          href: "in_class_ex/in_class_ex03/in_class_ex03.html"
        - text: "4 Geographically Weighted Summary Statistics - GWmodel methods"
          href: "in_class_ex/in_class_ex04/in_class_ex04.html"
    - text: "Take-home Exercises"
      menu:
        - text: "1. Geospatial Analytics for Public Good"
          href: "take_home_ex/take_home_ex01/take_home_ex01.html"
    right:
      - href: index.qmd
        text: Home
      - icon: linkedin
        href: https://www.linkedin.com/in/chrismanafe/
        aria-label: Linkedin
      - icon: github
        href: https://github.com/chrismanafe
        aria-label: Github

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

